---
- hosts: test peers
  tasks:
    - name: Enable NIC multiple queue
      command: /root/workspace/scripts/config_mqueue.sh enable

    - name: Enable irqbalance service
      service:
        name: irqbalance
        state: restarted
