- hosts: localhost
  connection: local

  vars_files:
    - ansible_vars.yml

  tasks:
    - name: Create disk
      ali_disk:
        disk_name: "{{ disk.disk_name }}"
        alicloud_region: "{{ global.alicloud_region }}"
        alicloud_zone: "{{ global.alicloud_zone }}"
        size: "{{ disk.disk_size }}"
        disk_category: "{{ disk.disk_category }}"
        disk_tags:
          - Name: AnsiblePerfTest
