- hosts: localhost
  connection: local

  vars_files:
    - ansible_vars.yml

  tasks:
    - name: Get VSwitch ID
      ali_vswitch_facts:
        alicloud_region: "{{ alicloud_region }}"
        name_prefix: "{{ vsw_name }}"
        filters:
          zone_id: "{{ alicloud_zone }}"
      register: vsw_facts

    - name: Get Group ID
      ali_security_group_facts:
        alicloud_region: "{{ alicloud_region }}"
        name_prefix: "{{ sg_name }}"
        filters:
          zone_id: "{{ alicloud_zone }}"
      register: sg_facts

    - name: Create a set of instances
      ali_instance:
        instance_name: "{{ instance_name }}"
        alicloud_region: "{{ alicloud_region }}"
        alicloud_zone: "{{ alicloud_zone }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami_id }}"
        host_name: "{{ instance_name }}"
        key_name: "{{ key_name }}"
        allocate_public_ip: true
        internet_charge_type: PayByTraffic
        max_bandwidth_out: 5
        vswitch_id: "{{ vsw_facts.vswitches[0].id }}"
        security_groups: "{{ sg_facts.groups[0].id }}"
        tags:
          Name: AnsiblePerfTest
        count: 1
        count_tag:
          Name: AnsiblePerfTest
      register: create_instance
