---
# - hosts: all
#   tasks:
#     - name: Create folders
#       file:
#         path: ~/workspace/log
#         state: directory
#         mode: "0755"

- hosts: test
  vars:
    local_bin: "./scripts"
    local_log: "./logs"
    remote_bin: "~/workspace"
    remote_log: "~/workspace/log"

  tasks:
    - name: Create folders
      file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      with_items:
        - "{{ remote_bin }}"
        - "{{ remote_log }}"

    - name: Deliver scripts to server
      copy:
        src: "{{ local_bin }}/{{ item }}"
        dest: "{{ remote_bin }}"
        mode: "0755"
      with_items:
        - master.sh
        - transmit.sh

    - name: Install sysstat package
      package:
        name:
          - sysstat
        state: present

    - name: Enable sysstat service
      service:
        name: sysstat
        state: started

    - name: Run test
      command: "{{ remote_bin }}/master.sh -c '192.168.8.29 192.168.8.28'"

    - name: Find logs
      find:
        paths: "{{ remote_log }}"
        patterns: "*.tar.gz"
      register: targets

    - name: Fetch logs
      fetch:
        src: "{{ item.path }}"
        dest: "{{ local_log }}/"
        flat: yes
      with_items: "{{ targets.files }}"
