---
- hosts: test peers
  tasks:
  - name: Install all the packages
    yum:
      name:
        - wget
        - make
        - gcc
      state: present

  - name: Create the directory if it does not exist
    file:
      path: /tmp/perftest-setup
      state: directory
      mode: '0755'

  - name: Download netperf tarball
    get_url:
      url: https://github.com/HewlettPackard/netperf/archive/netperf-2.7.0.tar.gz
      dest: /tmp/perftest-setup/netperf-2.7.0.tar.gz

  - name: Extract the tarball
    unarchive:
      src: /tmp/perftest-setup/netperf-2.7.0.tar.gz
      dest: /tmp/perftest-setup/
      remote_src: yes

  - name: Install the netperf tools (./configure)
    command: ./configure 
    args:
      chdir: /tmp/perftest-setup/netperf-netperf-2.7.0
  - name: Install the netperf tools (make)
    command: make
    args:
      chdir: /tmp/perftest-setup/netperf-netperf-2.7.0
  - name: Install the netperf tools (make install)
    command: make install
    args:
      chdir: /tmp/perftest-setup/netperf-netperf-2.7.0

  - name: Check the netperf tools
    command: netperf -V; netserver -V

